name: Docker CI/CD Build, Push & Deploy

on:
  push:
    branches: [ main ]  # Trigger on main branch commits

env:
  DOCKER_REPO: abhineshmathew/club-malabari-web
  IMAGE_TAG: latest

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1️⃣ Checkout source
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Set up QEMU (for multi-platform builds)
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # 3️⃣ Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 4️⃣ Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 5️⃣ Build and Push Docker Image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./web
        file: ./web/Dockerfile
        push: true
        tags: abhineshmathew/club-malabari-web:latest

    # 6️⃣ Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.8

    # 7️⃣ Initialize Terraform
    - name: Terraform Init
      working-directory: ./web/CD
      run: terraform init

    # 8️⃣ Validate Terraform configuration
    - name: Terraform Validate
      working-directory: ./web/CD
      run: terraform validate

    # 9️⃣ Apply Terraform (auto-approve)
    - name: Terraform Apply
      working-directory: ./web/CD
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: terraform apply -auto-approve
